version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
        
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*